// AUTO-GENERATED by scripts/gen-content-index.mjs — do not edit by hand.
export type ArticleIndexEntry = { slug: string; title: string; category: string };
export const articleIndex: ArticleIndexEntry[] = [
  {
    "slug": "the-two-families-of-vitamins",
    "title": "The two families of vitamins",
    "category": "vitamins"
  }
];
